// Generated by CoffeeScript 1.6.3
(function() {
  var canvasTiles, map, sinh, tile2coordZoom;

  mapElem.style.width = window.innerWidth + "px";

  mapElem.style.height = window.innerHeight + "px";

  mapElem.style.display = "inline-block";

  mapElem.style.position = "absolute";

  mapElem.style.top = mapElem.style.left = "0px";

  map = L.map('mapElem');

  L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);

  navigator.geolocation.getCurrentPosition(function(pos) {
    return map.setView([pos.coords.latitude, pos.coords.longitude], 13);
  });

  sinh = function(x) {
    return (Math.pow(Math.E, x) - Math.pow(Math.E, -x)) / 2;
  };

  tile2coordZoom = function(zoom) {
    return function(x, y) {
      var scale;
      scale = Math.pow(0.5, zoom);
      return [x * scale * 360.0 - 180.0, 180 / Math.PI * Math.atan(sinh(Math.PI * (1 - 2 * y * scale)))];
    };
  };

  canvasTiles = L.tileLayer.canvas();

  canvasTiles.drawTile = function(canvas, tilePoint, zoom) {
    var ctx, lat, lng, tile2coord, x, y, _ref;
    tile2coord = tile2coordZoom(zoom);
    x = tilePoint.x;
    y = tilePoint.y;
    _ref = tile2coord(x, y), lat = _ref[0], lng = _ref[1];
    console.log(lat, lng, tile2coord(x + 1, y + 1));
    ctx = canvas.getContext("2d");
    return ctx.fillRect(1, 0, 10, 10);
  };

  canvasTiles.addTo(map);

  /*
  heatmapLayer = L.TileLayer.heatMap
    radius: 20
    opacity: 0.8
    gradient:
      0.45: "rgb(0,0,255)"
      0.55: "rgb(0,255,255)"
      0.65: "rgb(0,255,0)"
    0.95: "yellow"
    1.0: "rgb(255,0,0)"
   
  testData =
    max: 46,
    data: ({lat: 33 +Math.random() * Math.random(), lon: 117 + Math.random() * Math.random(), value: 1} for i in [1..100])
  
  console.log testData
  
  
  heatmapLayer.addData testData.data
   
  overlayMaps = { 'Heatmap': heatmapLayer }
   
  controls = L.control.layers(null, overlayMaps, {collapsed: false})
   
  map = new L.Map('map',
    center: new L.LatLng(51.505, -0.09)
    zoom: 6
    layers: [baseLayer, heatmapLayer])
   
  controls.addTo map
  */


}).call(this);
